---
title: "Visualization"
author: "C. McBride"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
rm(flights)
## Executive Summary

The FAA also administers federal funds for the maintenaince and improvement of commercial airports. Decisions on the allocation of those funds are made annually and are based on, among other factors, flight and passenger volume. Data from the BTS plays an essential role in the approval of grant applications. I've chosen this particular dataset because I would like to practice working with high volume data. 

For this analysis, I will examine several of the most recent years of data with two goals: first, to find out how federal expenditure on airport improvement has benefited travelers, and second what airports would most benefit from receiving funding for the coming year. Out of this inquiry will come a visualization aimed at decision makers involved in funding allocation to better inform their decisions.

## The Why

Identify airports most eligible for API grants.

Applicants for grants through the AIP are required to prove that the proposed improvements are justified based primarily on demand for services at the applicant airport. Normally, it's incumbent on the airports to apply individually for AIP grant funds through specific and detailed project proposals. In this case, however, the complete flights dataset for all airports within the NPIAS will be analyzed for candidate airports. The conclusions for the report will be a list of airports most in need of AIP grants for improvements necessary to meet civil air-transportation demand.Benefits-cost analysis.

## The Who

The report and visualizations will be directed toward the FAA Airport Improvement Project review board. The board consists of industry professional well-versed in all aspects of the industry and sufficiently numerate to appreciate complex multivariable analysis and fully understand conclusions inferred from the data.


## The What
The Bureau of Transportation Statistics through the Federal Aviation Administration tracks flight log data for all commercial and private flights originating from or terminating in the United States. 
The Bureau of Transportation Statistics archives and makes openly available detailed flight log data from all flights originating or terminating within the United States. The data is organized by year and includes record of origin and destination, delays in departure and arrival, and aircraft type among others. In order to meet the goals of the report, additional data sets will be brought into the analysis, specifically weather and passenger volume along with data about the infrastructure of individual airports.

## The How

Through several single page infographics, one each for the candidate airports, viewed primarily on desktop or laptop computers. The Bureau of Transportation Statistics through the Federal Aviation Administration tracks flight log data for all commercial and private flights originating from or terminating in the United States. 

## Challenges

There will be two main challenges that I foresee. First, is the sheer volume of the data. In order to derive meaningful conclusions from the data, it will be necessary to include all of it in the analysis. This will require working with data tools that are new to me and effectively and efficiently querying the data besides building an clear, concise visualization. The second challenge is choosing metrics to answer the questions the stakeholders have. The associations between many of the features in the data are nuanced and not individually significantly correlated. For this reason, coming to conclusions that I can support with the data will require a greater analysis on my part.